$ErrorActionPreference='Stop'
$root=(Get-Location).Path; $source=$env:AIRPORTS_SOURCE
if(-not $source){$source=Join-Path $root 'airports.csv'}
$output=Join-Path $root 'src\data\airports.json'
if(-not (Test-Path -LiteralPath $source)){Set-Content -LiteralPath $output -Value '[]' -Encoding utf8; Write-Warning 'No airports source found.'; exit 0}
$bytes=[IO.File]::ReadAllBytes($source); $magic=([BitConverter]::ToString($bytes[0..3])).Replace('-','')
function Get-Text($zip,$name){$e=$zip.GetEntry($name);if(-not $e){return ''};$r=[IO.StreamReader]::new($e.Open());try{return $r.ReadToEnd()}finally{$r.Dispose()}}
function ColNum($ref){$letters=($ref -replace '\d','');$n=0;foreach($c in $letters.ToCharArray()){$n=$n*26+([int][char]$c-64)};return $n-1}
if($magic -ne '504B0304'){throw 'The supplied airport source is not OpenXML/XLSX.'}
Add-Type -AssemblyName System.IO.Compression.FileSystem
$zip=[IO.Compression.ZipFile]::OpenRead($source);try{
 [xml]$sharedXml=Get-Text $zip 'xl/sharedStrings.xml';$shared=@();if($sharedXml.sst.si){foreach($si in $sharedXml.sst.si){$shared+=($si.InnerText)}}
 [xml]$sheetXml=Get-Text $zip 'xl/worksheets/sheet1.xml';$ns=New-Object Xml.XmlNamespaceManager($sheetXml.NameTable);$ns.AddNamespace('x','http://schemas.openxmlformats.org/spreadsheetml/2006/main');$rowNodes=$sheetXml.SelectNodes('//x:sheetData/x:row',$ns);$matrix=@()
 foreach($row in $rowNodes){$cells=@{};foreach($c in $row.SelectNodes('x:c',$ns)){$v=$c.SelectSingleNode('x:v',$ns);$value=if($v){$v.InnerText}else{''};if($c.t -eq 's' -and $value -ne ''){$value=$shared[[int]$value]};if($c.t -eq 'inlineStr'){$value=$c.InnerText};$cells[(ColNum $c.r)]=$value};$max=if($cells.Keys.Count){($cells.Keys|Measure-Object -Maximum).Maximum}else{-1};$arr=@();for($i=0;$i -le $max;$i++){$arr+=if($cells.ContainsKey($i)){$cells[$i]}else{''}};$matrix+=,@($arr)}
}finally{$zip.Dispose()}
if($matrix.Count -lt 2){throw 'No usable worksheet rows found.'};$headers=$matrix[0]|ForEach-Object {[string]$_};$rows=@();$repairedRows=0;for($i=1;$i -lt $matrix.Count;$i++){ $r=[ordered]@{};$pos=0;for($j=0;$j -lt $headers.Count;$j++){ $value=if($pos -lt $matrix[$i].Count){[string]$matrix[$i][$pos]}else{''};$pos++;if($value -match '^\s*[\[\{]'){while($true){$candidate=$value -replace '""','"';if($candidate.EndsWith(']"') -or $candidate.EndsWith('}"')){$candidate=$candidate.Substring(0,$candidate.Length-1)};try{$null=$candidate|ConvertFrom-Json -ErrorAction Stop;$value=$candidate;break}catch{if($pos -ge $matrix[$i].Count){break};$value+=','+[string]$matrix[$i][$pos];$pos++;$repairedRows++}}};$r[$headers[$j]]=$value};$rows+=,[pscustomobject]$r}
$allowed=@('source_file','document_title','service_name','aliases','summary','official_url','affiliate_url','affiliate_code','registration_url','telegram_url','currency','operating_info','line_architecture','protocols','node_regions_raw','node_regions_standardized','bandwidth_or_speed_claims','device_or_usage_limits','client_support','platforms','payment_methods','free_trial','refund_policy','discounts_or_coupon','unlock_support_from_overview','streaming_services_mentioned','ai_services_mentioned','lowest_direct_monthly_price_cny','lowest_listed_annual_price_cny','lowest_listed_one_time_price_cny','plan_rows_count','plans_json','test_or_performance_data_json','feature_bullets','purchase_advice','verification_status','verification_level','source_url','last_checked_at','source_type','is_excluded','exclusion_reason','affiliate_code_mismatch','data_quality_flags')
$records=@{};$warnings=[Collections.Generic.List[string]]::new();foreach($row in $rows){$item=[ordered]@{};foreach($f in $allowed){$p=$row.PSObject.Properties[$f];$item[$f]=if($p){[string]$p.Value}else{''}};$name=$item['service_name'].Trim();if(-not $name){$warnings.Add("Row missing service_name");continue};$canonical=($name -replace '（原.*?）|\(原.*?\)','').Trim();if($records.ContainsKey($canonical)){$warnings.Add("Deduplicated service_name: $canonical");continue};$slug=($canonical.ToLower() -replace '（.*?）|\(.*?\)','' -replace '[^a-z0-9\u4e00-\u9fff]+','-').Trim('-');$item['slug']=$slug;$nativeText=[string]$item['summary']+' '+[string]$item['operating_info']+' '+[string]$item['feature_bullets']+' '+[string]$item['unlock_support_from_overview'];$item['native_ip_declared']=if($nativeText -match '原生\s*IP'){$true}else{$false};$item['ip_profile']=if($item['native_ip_declared']){'服务商声明提供原生 IP'}else{''};$records[$canonical]=[pscustomobject]$item;if(-not $item['summary']){$warnings.Add("$canonical`: missing summary")};if(-not $item['affiliate_url']){$warnings.Add("$canonical`: missing affiliate_url")}}
$normalized=@($records.Values);$nativeNeedle=[string]([char]0x539F)+[char]0x751F;foreach($entry in $normalized){$entry.native_ip_declared=(([string]$entry.summary).Contains($nativeNeedle) -and ([string]$entry.summary -match 'IP'));$entry.ip_profile=''};$data=$normalized|ConvertTo-Json -Depth 8;Set-Content -LiteralPath $output -Value $data -Encoding utf8
$quality="# Data Quality Report`n`n- Source: $source`n- Magic bytes: $magic (OpenXML / XLSX)`n- Rows read: $($rows.Count)`n- Canonical services: $($records.Count)`n- Native IP declarations: $(@($normalized|Where-Object native_ip_declared).Count)`n- Repaired split JSON-like cells: $repairedRows`n`n## Warnings`n`n"+$(if($warnings.Count){($warnings|ForEach-Object{"- $_"}) -join "`n"}else{'- None'})+"`n`nService claims are retained as source material and are not independent verification.`n";Set-Content -LiteralPath (Join-Path $root 'DATA_QUALITY_REPORT.md') -Value $quality -Encoding utf8;Write-Host "Normalized $($records.Count) services from $($rows.Count) rows."
